"use client";
import { useState,useEffect,useRef,useCallback, type PointerEvent as RPointerEvent, type CSSProperties } from "react";
import { Plus, Layers, ImagePlus, Pin, Move, Tag, StickyNote, Minus, Maximize, Pencil, Link as LinkIcon, Trash2, Check, Loader2, Grip, X, UploadCloud } from "lucide-react";
import { Sidebar,SidebarProvider,SidebarContent,SidebarHeader,SidebarFooter,SidebarTrigger } from "@/components/ui/sidebar";
import { Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription } from "@/components/ui/sheet";
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from "@/components/ui/dialog";
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from "@/components/ui/alert-dialog";
import { Empty } from "@/components/ui/empty";
import { Toaster,toast } from "sonner";
type Board={id:string;name:string;created:number};
type Card={id:string;board_id:string;kind:"image"|"note";title:string;description:string;reference:string;tags:string[];image:string|null;x:number;y:number;created:number};
type Draft={title:string;description:string;reference:string;tags:string};
async function api(data?:object|FormData){const r=await fetch("/api/workspace",data?{method:"POST",headers:data instanceof FormData?undefined:{"Content-Type":"application/json"},body:data instanceof FormData?data:JSON.stringify(data)}:{cache:"no-store"});const body=await r.json() as {error?:string;boards:Board[];cards:Card[];board:Board;card:Card};if(!r.ok)throw new Error(body.error||"ไม่สามารถบันทึกข้อมูลได้");return body;}
const errorText=(e:unknown)=>e instanceof Error?e.message:"เกิดข้อผิดพลาด กรุณาลองอีกครั้ง";
export default function Home(){
 const [boards,setBoards]=useState<Board[]>([]),[cards,setCards]=useState<Card[]>([]),[active,setActive]=useState(""),[loaded,setLoaded]=useState(false),[loadError,setLoadError]=useState(""),[busy,setBusy]=useState(false),[status,setStatus]=useState("พร้อมเก็บไอเดีย"),[filter,setFilter]=useState(""),[zoom,setZoom]=useState(1),[over,setOver]=useState(false);
 const [selected,setSelected]=useState<string|null>(null),[draft,setDraft]=useState<Draft>({title:"",description:"",reference:"",tags:""}),[dialog,setDialog]=useState<"create"|"rename"|null>(null),[boardName,setBoardName]=useState(""),[deleteId,setDeleteId]=useState<string|null>(null);
 const input=useRef<HTMLInputElement>(null),viewport=useRef<HTMLDivElement>(null),lock=useRef(false),boardPromise=useRef<Promise<Board>|null>(null);
 const moving=useRef<{id:string;px:number;py:number;x:number;y:number;cx:number;cy:number;scrollX:number;scrollY:number;moved:boolean}|null>(null),pan=useRef<{px:number;py:number;x:number;y:number}|null>(null);
 const board=boards.find(b=>b.id===active),all=cards.filter(c=>c.board_id===active),visible=all.filter(c=>!filter||c.tags.includes(filter)),tags=[...new Set(all.flatMap(c=>c.tags))],current=cards.find(c=>c.id===selected);
 const load=useCallback(async()=>{try{setLoadError("");const data=await api();setBoards(data.boards);setCards(data.cards);setActive(a=>data.boards.some((b:Board)=>b.id===a)?a:data.boards[0]?.id||"");setLoaded(true)}catch(e){setLoadError(errorText(e));setLoaded(true)}},[]);
 useEffect(()=>{void load()},[load]);
 async function ensureBoard(){if(active)return boards.find(b=>b.id===active)!;if(boardPromise.current)return boardPromise.current;boardPromise.current=api({action:"createBoard",name:"แคนวาสแรกของฉัน"}).then(d=>{setBoards(bs=>[...bs,d.board]);setActive(d.board.id);return d.board});try{return await boardPromise.current!}finally{boardPromise.current=null}}
 function edit(c:Card){setSelected(c.id);setDraft({title:c.title,description:c.description,reference:c.reference,tags:c.tags.join(", ")})}
 async function run(action:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setStatus("กำลังบันทึก…");try{await action();setStatus("บันทึกแล้ว")}catch(e){setStatus("บันทึกไม่สำเร็จ");toast.error(errorText(e))}finally{lock.current=false;setBusy(false)}}
 function place(i=0){return {x:Math.max(24,Math.round((viewport.current?.scrollLeft||0)/zoom+36+(i%3)*286)),y:Math.max(24,Math.round((viewport.current?.scrollTop||0)/zoom+32+Math.floor(i/3)*340))}}
 async function upload(files:FileList|File[]|null){if(!files?.length||!loaded||loadError)return;const list=Array.from(files);await run(async()=>{const b=await ensureBoard();setFilter("");let count=0;for(let i=0;i<list.length;i++){const file=list[i];if(file.size>10*1024*1024){toast.error(file.name+": รูปต้องไม่เกิน 10 MB");continue}const f=new FormData();f.set("file",file);f.set("boardId",b.id);const p=place(i);f.set("x",String(p.x));f.set("y",String(p.y));try{setStatus("กำลังอัปโหลด "+(i+1)+"/"+list.length);const d=await api(f);setCards(cs=>[...cs,d.card]);count++}catch(e){toast.error(file.name+": "+errorText(e))}}if(count)toast.success("เพิ่มรูปภาพแล้ว "+count+" รูป");else throw new Error("ยังไม่มีรูปที่อัปโหลดสำเร็จ กรุณาลองอีกครั้ง")});if(input.current)input.current.value=""}
 async function addNote(){await run(async()=>{const b=await ensureBoard();const d=await api({action:"createNote",id:b.id,...place()});setCards(cs=>[...cs,d.card]);setFilter("");edit(d.card)})}
 async function saveBoard(){const name=boardName.trim();if(!name)return;await run(async()=>{if(dialog==="rename"&&board){await api({action:"renameBoard",id:board.id,name});setBoards(bs=>bs.map(b=>b.id===board.id?{...b,name}:b))}else{const d=await api({action:"createBoard",name});setBoards(bs=>[...bs,d.board]);setActive(d.board.id);setFilter("");setZoom(1);viewport.current?.scrollTo(0,0)}setDialog(null)})}
 function switchBoard(id:string){if(lock.current)return;setActive(id);setSelected(null);setFilter("");setZoom(1);viewport.current?.scrollTo(0,0)}
 async function saveCard(){if(!current||!draft.title.trim())return;const payload={title:draft.title.trim(),description:draft.description,reference:draft.reference,tags:[...new Set(draft.tags.split(/[,，\n]/).map(t=>t.trim().replace(/^#/,"")).filter(Boolean))]};await run(async()=>{await api({action:"updateCard",id:current.id,...payload});setCards(cs=>cs.map(c=>c.id===current.id?{...c,...payload}:c));setSelected(null);toast.success("บันทึกรายละเอียดแล้ว")})}
 function startDrag(e:RPointerEvent,c:Card){if(lock.current||e.button!==0)return;e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);moving.current={id:c.id,px:e.clientX,py:e.clientY,x:c.x,y:c.y,cx:c.x,cy:c.y,scrollX:viewport.current?.scrollLeft||0,scrollY:viewport.current?.scrollTop||0,moved:false};setCards(cs=>[...cs.filter(v=>v.id!==c.id),c])}
 function drag(e:RPointerEvent){const m=moving.current;if(!m)return;const dx=e.clientX-m.px,dy=e.clientY-m.py;if(Math.abs(dx)+Math.abs(dy)>4)m.moved=true;const x=Math.min(20000,Math.max(0,Math.round(m.x+(dx+(viewport.current?.scrollLeft||0)-m.scrollX)/zoom))),y=Math.min(20000,Math.max(0,Math.round(m.y+(dy+(viewport.current?.scrollTop||0)-m.scrollY)/zoom)));m.cx=x;m.cy=y;setCards(cs=>cs.map(c=>c.id===m.id?{...c,x,y}:c))}
 async function stopDrag(cancel=false){const m=moving.current;moving.current=null;if(!m)return;if(cancel){setCards(cs=>cs.map(c=>c.id===m.id?{...c,x:m.x,y:m.y}:c));return}if(!m.moved){const c=cards.find(c=>c.id===m.id);if(c)edit(c);return}await run(async()=>{try{await api({action:"moveCard",id:m.id,x:m.cx,y:m.cy})}catch(e){setCards(cs=>cs.map(c=>c.id===m.id?{...c,x:m.x,y:m.y}:c));throw e}})}
 function nudge(e:React.KeyboardEvent,c:Card){if(!["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(e.key)||lock.current)return;e.preventDefault();const step=e.shiftKey?40:10;const x=Math.max(0,Math.min(20000,c.x+(e.key==="ArrowRight"?step:e.key==="ArrowLeft"?-step:0))),y=Math.max(0,Math.min(20000,c.y+(e.key==="ArrowDown"?step:e.key==="ArrowUp"?-step:0)));void run(async()=>{await api({action:"moveCard",id:c.id,x,y});setCards(cs=>cs.map(v=>v.id===c.id?{...v,x,y}:v))})}
 function fit(){const w=Math.max(...all.map(c=>c.x+300),700),h=Math.max(...all.map(c=>c.y+380),500);setZoom(Math.max(.25,Math.min(1,(viewport.current?.clientWidth||1000)/w,(viewport.current?.clientHeight||600)/h)));viewport.current?.scrollTo(0,0)}
 useEffect(()=>{type Registry={registerTool:(t:object,o:{signal:AbortSignal})=>void|Promise<void>};const registry=(document as Document & {modelContext?:Registry}).modelContext;if(!registry)return;const life=new AbortController();const register=(t:object)=>{try{void Promise.resolve(registry.registerTool(t,{signal:life.signal})).catch(()=>{})}catch{}};register({name:"list_canvases",title:"ดูแคนวาส",description:"Read saved canvases and note metadata for the signed-in user.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>api()});register({name:"create_canvas",title:"สร้างแคนวาส",description:"Create a saved canvas and select it in Pinspace.",inputSchema:{type:"object",properties:{name:{type:"string",minLength:1,maxLength:100}},required:["name"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=="object"||!("name" in input)||typeof input.name!=="string"||!input.name.trim()||input.name.length>100)throw new Error("ชื่อแคนวาสต้องมี 1–100 ตัวอักษร");if(lock.current)throw new Error("กำลังบันทึก กรุณาลองอีกครั้ง");const d=await api({action:"createBoard",name:input.name.trim()});setBoards(bs=>[...bs,d.board]);setActive(d.board.id);setFilter("");return d.board}});return()=>life.abort()},[]);
 const title=board?.name||"แคนวาสแรกของฉัน",width=Math.max(1200,...all.map(c=>c.x+320)),height=Math.max(850,...all.map(c=>c.y+460));
 return <SidebarProvider style={{"--sidebar-width":"250px"} as CSSProperties}><Toaster position="bottom-right" richColors/><input hidden ref={input} type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>void upload(e.target.files)}/>
 <Sidebar><SidebarHeader><div className="brand"><span className="brand-icon"><Pin size={22}/></span>pinspace<span className="brand-dot">.</span></div></SidebarHeader><SidebarContent><div className="side-label">พื้นที่ของคุณ <span>{boards.length}</span></div>{boards.map(b=><button disabled={busy} key={b.id} className={"board-link "+(active===b.id?"active":"")} onClick={()=>switchBoard(b.id)}><Layers size={18}/><strong>{b.name}</strong><span>{cards.filter(c=>c.board_id===b.id).length}</span></button>)}{!boards.length&&<div className="board-link active"><Layers size={18}/><strong>{title}</strong><span>0</span></div>}<button disabled={!loaded||!!loadError||busy} className="new-board" onClick={()=>{setBoardName("");setDialog("create")}}><Plus size={17}/>สร้างแคนวาสใหม่</button><div className="sidebar-tip"><span className="tip-icon"><StickyNote size={19}/></span><p>รูปที่ใช่ ไอเดียที่ชอบ<br/>มีที่อยู่แล้ว</p><small>แต่ละแคนวาส คืออีกหนึ่งพื้นที่<br/>ให้ความคิดได้เติบโต</small></div></SidebarContent><SidebarFooter><div className="side-footer"><span className="avatar">P</span><div>พื้นที่ส่วนตัว<small>เก็บทุกไอเดียไว้ด้วยกัน</small></div></div></SidebarFooter></Sidebar>
 <main className="main"><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><span>แคนวาสของฉัน</span><span>/</span><strong>{title}</strong></div><span className="save-status" role="status">{busy?<Loader2 size={14} className="spin"/>:<Check size={14}/>} {status}</span></header>
 <div className="board-heading"><div><div className="eyebrow">YOUR VISUAL SPACE</div><h1>{title}{board&&<button className="icon-button rename" aria-label="เปลี่ยนชื่อแคนวาส" disabled={busy} onClick={()=>{setBoardName(title);setDialog("rename")}}><Pencil size={15}/></button>}</h1><p>{all.filter(c=>c.kind==="image").length} รูปภาพ <span>·</span> {all.filter(c=>c.kind==="note").length} โน้ต</p></div><div className="heading-actions"><button className="secondary" disabled={busy||!loaded||!!loadError} onClick={()=>void addNote()}><StickyNote size={17}/><span>เพิ่มโน้ต</span></button><button className="primary" disabled={busy||!loaded||!!loadError} onClick={()=>input.current?.click()}>{busy?<Loader2 size={18} className="spin"/>:<Plus size={19}/>}เพิ่มรูปภาพ</button></div></div>
 <div className="filterbar"><div className="tag-filters"><button onClick={()=>setFilter("")} className={"filter-chip "+(!filter?"chosen":"")}><Layers size={15}/>ทั้งหมด <b>{all.length}</b></button>{tags.map(t=><button key={t} className={"filter-chip "+(filter===t?"chosen":"")} onClick={()=>setFilter(filter===t?"":t)}><Tag size={13}/>{t}</button>)}</div><span className="tiny-help"><Move size={15}/>ลากเพื่อจัดวาง · คลิกเพื่อแก้ไข</span></div>
 <section ref={viewport} className={"canvas "+(over?"drop-active":"")} aria-label="พื้นที่แคนวาส" onDragOver={e=>{e.preventDefault();setOver(true)}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setOver(false)}} onDrop={e=>{e.preventDefault();setOver(false);void upload(e.dataTransfer.files)}} onPointerDown={e=>{if(e.button!==0||e.target!==e.currentTarget)return;pan.current={px:e.clientX,py:e.clientY,x:e.currentTarget.scrollLeft,y:e.currentTarget.scrollTop};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(pan.current){e.currentTarget.scrollLeft=pan.current.x+pan.current.px-e.clientX;e.currentTarget.scrollTop=pan.current.y+pan.current.py-e.clientY}}} onPointerUp={()=>pan.current=null} onPointerCancel={()=>pan.current=null}>
 {loadError?<Empty className="empty-board"><h2>เปิดแคนวาสไม่ได้ชั่วคราว</h2><p>{loadError}</p><div className="heading-actions"><button className="primary" onClick={()=>void load()}>ลองอีกครั้ง</button><a className="secondary" href="/signin-with-chatgpt?return_to=/" target="_top">เข้าสู่ระบบ</a></div></Empty>:!loaded?<Empty className="empty-board"><Loader2 className="spin"/><p>กำลังเปิดแคนวาส…</p></Empty>:all.length===0?<Empty className="empty-board"><div className="empty-icon"><ImagePlus size={35}/></div><span className="eyebrow">A LITTLE SPACE, A LOT OF IDEAS</span><h2>ไอเดียแรก เริ่มจากรูปเดียว</h2><p>วางภาพที่ชอบ เติมโน้ตและแหล่งอ้างอิง<br/>แล้วจัดวางให้เป็นบอร์ดในแบบของคุณ</p><button className="primary" disabled={busy} onClick={()=>input.current?.click()}><ImagePlus size={18}/>อัปโหลดรูปแรก</button><small>หรือลากรูปมาวางที่นี่ · สูงสุด 10 MB ต่อรูป<br/>JPG, PNG, WebP, GIF</small></Empty>:<div className="world-size" style={{width:width*zoom,height:height*zoom,pointerEvents:"none"}}><div className="world" style={{width,height,transform:"scale("+zoom+")",pointerEvents:"none"}}>{visible.map((c,i)=><article key={c.id} className={"note-card "+(c.kind==="note"?"text-note":"")} style={{left:c.x,top:c.y,zIndex:i+1,pointerEvents:"auto"}}><button className="card-drag" aria-label={"เปิดหรือลาก "+c.title} onPointerDown={e=>startDrag(e,c)} onPointerMove={drag} onPointerUp={()=>void stopDrag()} onPointerCancel={()=>void stopDrag(true)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();edit(c)}else nudge(e,c)}}><span>{c.kind==="image"?<ImagePlus size={13}/>:<StickyNote size={13}/>} {c.kind==="image"?"รูปภาพ":"โน้ต"}</span><Grip size={15}/></button>{c.image&&<button className="card-image" aria-label={"แก้ไข "+c.title} onPointerDown={e=>startDrag(e,c)} onPointerMove={drag} onPointerUp={()=>void stopDrag()} onPointerCancel={()=>void stopDrag(true)} onClick={e=>{if(e.detail===0)edit(c)}}><img src={c.image} alt={c.title} draggable={false}/></button>}<button className="card-body" onClick={()=>edit(c)}><h2>{c.title}</h2>{c.description&&<p>{c.description}</p>}{c.reference&&<span className="card-reference"><LinkIcon size={12}/>{c.reference}</span>}{!c.description&&!c.reference&&<p className="card-placeholder">คลิกเพื่อเติมรายละเอียด…</p>}</button>{c.tags.length>0&&<div className="card-tags">{c.tags.map(t=><button key={t} onClick={()=>setFilter(filter===t?"":t)}>{t}</button>)}</div>}</article>)}</div></div>}
 {filter&&!visible.length&&<Empty className="empty-board"><h2>ไม่มีรูปที่ใช้แท็กนี้</h2><button className="secondary" onClick={()=>setFilter("")}>ดูทั้งหมด</button></Empty>}
 {over&&<div className="drop-overlay"><UploadCloud size={42}/><strong>ปล่อยรูปเพื่อเพิ่มลงแคนวาส</strong></div>}
 </section><div className="canvas-bottom"><span><Pin size={14}/>ปักรูป เก็บไอเดีย</span><div className="zoom-controls"><button aria-label="ย่อ" onClick={()=>setZoom(z=>Math.max(.25,z-.1))}><Minus size={16}/></button><button aria-label="รีเซ็ตขนาด 100%" onClick={()=>setZoom(1)}>{Math.round(zoom*100)}%</button><button aria-label="ขยาย" onClick={()=>setZoom(z=>Math.min(2,z+.1))}><Plus size={16}/></button><i/><button aria-label="แสดงการ์ดทั้งหมด" onClick={fit}><Maximize size={17}/></button></div><span className="board-number">PINSPACE / {String(Math.max(1,boards.findIndex(b=>b.id===active)+1)).padStart(2,"0")}</span></div></main>
 <Dialog open={dialog!==null} onOpenChange={v=>{if(!v&&!busy)setDialog(null)}}><DialogContent><DialogHeader><DialogTitle>{dialog==="rename"?"เปลี่ยนชื่อแคนวาส":"พื้นที่ใหม่สำหรับไอเดียใหม่"}</DialogTitle><DialogDescription>ตั้งชื่อให้จำได้ง่าย เช่น ไอเดียห้องนอน หรือ โปรเจกต์ถัดไป</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();void saveBoard()}} className="form"><label htmlFor="board-name">ชื่อแคนวาส</label><input id="board-name" autoFocus maxLength={100} value={boardName} onChange={e=>setBoardName(e.target.value)} placeholder="แคนวาสของฉัน" required/><button className="primary" disabled={busy||!boardName.trim()} type="submit">{busy?"กำลังบันทึก…":dialog==="rename"?"บันทึกชื่อ":"สร้างแคนวาส"}</button></form></DialogContent></Dialog>
 <Sheet open={!!selected} onOpenChange={v=>{if(!v&&!busy)setSelected(null)}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>รายละเอียด{current?.kind==="note"?"โน้ต":"รูปภาพ"}</SheetTitle><SheetDescription>เก็บบริบทไว้ กลับมาดูเมื่อไรก็เข้าใจ</SheetDescription></SheetHeader>{current&&<form className="form detail-form" onSubmit={e=>{e.preventDefault();void saveCard()}}>{current.image&&<img className="detail-image" src={current.image} alt={current.title}/>}<label htmlFor="card-title">ชื่อ{current.kind==="note"?"โน้ต":"รูปภาพ"}</label><input id="card-title" value={draft.title} maxLength={120} required onChange={e=>setDraft({...draft,title:e.target.value})}/><label htmlFor="card-description">รายละเอียด / สิ่งที่ชอบในรูปนี้</label><textarea id="card-description" rows={5} maxLength={10000} value={draft.description} placeholder="ไอเดียที่ได้ สีที่ชอบ หรือรายละเอียดที่อยากจำ…" onChange={e=>setDraft({...draft,description:e.target.value})}/><label htmlFor="card-reference"><LinkIcon size={15}/>แหล่งอ้างอิง</label><textarea id="card-reference" rows={2} maxLength={2000} value={draft.reference} placeholder="ลิงก์ ชื่อศิลปิน หนังสือ หรือที่มาของรูป" onChange={e=>setDraft({...draft,reference:e.target.value})}/>{/^https?:\/\/\S+$/.test(draft.reference.trim())&&<a className="reference-link" href={draft.reference.trim()} target="_blank" rel="noopener noreferrer">เปิดแหล่งอ้างอิง</a>}<label htmlFor="card-tags"><Tag size={15}/>แท็ก</label><input id="card-tags" value={draft.tags} onChange={e=>setDraft({...draft,tags:e.target.value})} placeholder="เช่น interior, สีฟ้า, ไอเดีย"/><small>คั่นแต่ละแท็กด้วยเครื่องหมาย , · ไม่เกิน 20 แท็ก</small><div className="detail-actions"><button className="delete-button" type="button" disabled={busy} onClick={()=>setDeleteId(current.id)}><Trash2 size={17}/>ลบ</button><button className="primary" type="submit" disabled={busy||!draft.title.trim()}>{busy?<Loader2 size={16} className="spin"/>:<Check size={16}/>}บันทึกรายละเอียด</button></div></form>}</SheetContent></Sheet>
 <AlertDialog open={!!deleteId} onOpenChange={v=>{if(!v)setDeleteId(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>ลบการ์ดนี้?</AlertDialogTitle><AlertDialogDescription>รูปภาพและรายละเอียดของการ์ดนี้จะถูกลบออกจากแคนวาส และกู้คืนไม่ได้</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>ยกเลิก</AlertDialogCancel><AlertDialogAction className="danger" onClick={()=>{const id=deleteId;void run(async()=>{await api({action:"deleteCard",id});setCards(cs=>cs.filter(c=>c.id!==id));setSelected(null);setDeleteId(null);toast.success("ลบการ์ดแล้ว")})}}>ลบการ์ด</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </SidebarProvider>
}



